### ISSUE TITLE
401: {"msg":"login required"} after being logged in while trying to download 

### ISSUE THREAD

**Issue by pzpzpzp2** [omniobject3d/OmniObject3D#42]
I'm trying to download the dataset through the openxlab cli interface. I've logged in with my SK and AK. I can ls the dataset. But when I try to download any of it 
```openxlab dataset download --dataset-repo OpenXDLab/OmniObject3D-New --source-path /raw/point_clouds/ply_files --target-path /app/omniobject3d```
I keep getting this error: 
```{"msg":"login required"}```
I already logged in as far as I can tell. Not sure what this error is about.

**Comment by omniobject3d** [comment]
Hi! We are not encountering this problem. Perhaps you can try using openxlab login --relogin to see if it resolves the issue. Alternatively, you can download the dataset from our Google Driven. We will further investigate if the problem with openxlab persists.

**Comment by pzpzpzp2** [comment]
I've tried --relogin a couple times already. The issue still persists. 
Are there things I need to bind to my account? I only had email attached. Now my github is linked too. 
The phone number binding is broken so I can't add that. I don't have wechat.

**Comment by MoH-assan** [comment]
Hi, 
I am having the same issue, 
To confirm the login I used `min` and it doesn't show login error, it shows `No dataset: OpenMMLab,` see below. 

`$ mim download mmaction2 --dataset kinetics700
/home/c/cglee/abubakr5/.local/lib/python3.9/site-packages/pandas/core/computation/expressions.py:21: UserWarning: Pandas requires version '2.8.4' or newer of 'numexpr' (version '2.8.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
Start downloading kinetics700 to data...
WARNING:This CLI tool is deprecated and will be removed in a future release.
The opendatalab(odl) pkg has been deprecated and will no longer be supported in few weeks.
We recommend that you switch to the openxlab pkg, which accept same username/password,
provides the same functionality and other enhanced AI friendly features.
More details please refer to https://openxlab.org.cn/datasets
No dataset: OpenMMLab
Traceback (most recent call last):
  File "/gpfs/fs0/scratch/c/cglee/abubakr5/.virtualenvs/BKRROugePython3_9/bin/mim", line 8, in <module>
    sys.exit(cli())
  File "/home/c/cglee/abubakr5/.local/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/c/cglee/abubakr5/.local/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/c/cglee/abubakr5/.local/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/c/cglee/abubakr5/.local/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/c/cglee/abubakr5/.local/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/gpfs/fs0/scratch/c/cglee/abubakr5/.virtualenvs/BKRROugePython3_9/lib/python3.9/site-packages/mim/commands/download.py", line 70, in cli
    download(package, configs, dest_root, check_certificate, dataset)
  File "/gpfs/fs0/scratch/c/cglee/abubakr5/.virtualenvs/BKRROugePython3_9/lib/python3.9/site-packages/mim/commands/download.py", line 110, in download
    return _download_dataset(package, dataset, dest_root)  # type: ignore
  File "/gpfs/fs0/scratch/c/cglee/abubakr5/.virtualenvs/BKRROugePython3_9/lib/python3.9/site-packages/mim/commands/download.py", line 242, in _download_dataset
    subprocess.check_call(['odl', 'get', src_name, '-d', download_root],
  File "/scinet/rouge/software/2021a/opt/base/python/3.9.10/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['odl', 'get', 'OpenMMLab/Kinetics_700', '-d', 'data']' returned non-zero exit status 255.
`

When I use `get,` I face the login issue
`$ openxlab dataset get --dataset-repo OpenMMLab/Kinetics_700
Fetching the list of datasets...
401: {"msg":"login required"}`

**Comment by MoH-assan** [comment]
> relogin 

@omniobject3d 
--relogin doesn't help,

**Comment by omniobject3d** [comment]
Hi, could you try updating the openxlab package to over 0.1.0? The new version won't raise errors like this.

**Comment by j93hahn** [comment]
@omniobject3d I get the same error when I try to download DOTAv1.5

I have `openxlab==0.1.1`

**Comment by lmdwhy** [comment]
Hi, I got the same problem. I did relogin and version update and that didn't help, but finally still reported as 401 error.
`(base) user:~/Desktop/omni$ openxlab login --relogin`
`openxlab: You can find your Access key & Secrete Key in your browser here: https://sso.openxlab.org.cn/usercenter?tab=secret`
`openxlab: Paste your Access Key here: <deleted>`
`openxlab: Paste your Secrete Key here: `
`(base) user:~/Desktop/omni$ openxlab dataset download --dataset-repo OpenXDLab/OmniObject3D-New --source-path /raw/point_clouds/ply_files --target-path test/`
`Fetching the list of files...`
`401: {"msg":"login required"}`
`(base) user:~/Desktop/omni$ openxlab version --update-check`
`You are using openxlab version 0.1.1, it is already the latest version.`
`(base) user:~/Desktop/omni$ openxlab dataset download --dataset-repo OpenXDLab/OmniObject3D-New --source-path /raw/point_clouds/ply_files --target-path test/`
`Fetching the list of files...`
`401: {"msg":"login required"}
`

**Comment by omniobject3d** [comment]
@lmdwhy Hi, it looks like that you have not login, could you please try to first sign up [here](https://sso.openxlab.org.cn/login), and then login by inputting your AK&SK at the terminal, and see if you could successfully download the data?

**Comment by lmdwhy** [comment]
> @lmdwhy Hi, it looks like that you have not login, could you please try to first sign up [here](https://sso.openxlab.org.cn/login), and then login by inputting your AK&SK at the terminal, and see if you could successfully download the data?

When I run `openxlab login`, it turns to`AK and SK have been configured. You can use the --relogin parameter to force a re-login.`
And I tried this before the relogin above. Does this mean the login was successful?

**Comment by wutong16** [comment]
I see. We have just tested on several more devices and accounts, and it turns out this issue primarily affects newly registered accounts. We have reached out to the platform to address this problem and will inform you as soon as it's resolved. In the meantime, you can use [Google Drive](https://drive.google.com/drive/u/0/folders/1-hlkTqUJR_J2xht1qztmX2xAq_qNw4vn) for downloading.

**Comment by omniobject3d** [comment]
> I see. We have just tested on several more devices and accounts, and it turns out this issue primarily affects newly registered accounts. We have reached out to the platform to address this problem and will inform you as soon as it's resolved. In the meantime, you can use [Google Drive](https://drive.google.com/drive/u/0/folders/1-hlkTqUJR_J2xht1qztmX2xAq_qNw4vn) for downloading.

Hi @j93hahn @MoH-assan @pzpzpzp2 @lmdwhy,

After testing on several more new accounts, we discovered that some of them can generate a valid AKSK, while others cannot. However, the valid AKSK can be shared across different accounts. Given this situation, could you please try using the following AKSK, which has been confirmed to work for accounts experiencing this issue?

AK: bmyqk5wpbaxl6x1vkzq9
SK: nl7kq9palyr6j3pwxolden7ezq4dwjmbgdm81yeo

**Comment by j93hahn** [comment]
The issue for me was that I was not logged into the website. If you log into both the CLI AND the website, then the download should work

The `401` message is complaining that you're not logged into the website @lmdwhy. Try logging in there too and it should work
